apiVersion: batch/v1
kind: Job
metadata:
  name: filipesantos-ml-job   
  namespace: filipesantos  
spec:
  template:
    spec:
      containers:
      - name: ml-generator
        image: pirolaa/ml-generator:v4
        volumeMounts:
        - name: model-storage       
          mountPath: /data          
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi" 
      volumes:
      - name: model-storage         
        persistentVolumeClaim:
          claimName: filipesantos-pvc 
      restartPolicy: Never 
  backoffLimit: 2 
